[build]
buildCommand = "npx prisma generate && npm run build"

[deploy]
startCommand = "until npx prisma db push --accept-data-loss --skip-generate; do echo 'DB não disponível ainda, aguardando...'; sleep 3; done && npm run start"
healthcheckPath = "/"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3
